name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        brew install swiftlint && swiftlint
    - name: Run tests
      run: |
        brew install swiftlint && swiftlint
