name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: swiftlint --strict
